# Generated by Django 4.1.7 on 2023-05-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='cpsw',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='register',
            name='psw',
            field=models.CharField(max_length=8),
        ),
    ]
